[workspace]
members = [ "ebc_2024", "new_year", "runner" ]
resolver = "2"

[workspace.dependencies]
ebc_2024 = { path = "ebc_2024" }
helper = { git = "https://github.com/mmitton/helper.git" }

[profile.release]
debug = true
